# Generated by Django 4.1.7 on 2023-03-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_tournamentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='application.tennisplayer'),
        ),
    ]
