# Generated by Django 4.1.7 on 2023-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_coach_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisplayer',
            name='tp_gender',
            field=models.CharField(default='X', max_length=10),
        ),
    ]
