# Generated by Django 4.1.7 on 2023-03-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_tennisplayer_tp_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(through='application.TournamentRegistration', to='application.tennisplayer'),
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='tr_player',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='tr_tournament',
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='tr_player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.tennisplayer'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='tr_tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.tournament'),
        ),
    ]
