# Generated by Django 4.1.7 on 2023-03-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_tournament_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentregistration',
            name='tr_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.tennisplayer'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='tr_tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.tournament'),
        ),
    ]
