# Generated by Django 4.1.7 on 2023-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_tournamentregistration_tr_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisplayer',
            name='tournaments',
            field=models.ManyToManyField(through='application.TournamentRegistration', to='application.tournament'),
        ),
    ]
