# Generated by Django 4.1.7 on 2023-05-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_tennisplayer_tournaments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tennisplayer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tournamentregistration',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='coach',
            name='c_description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['player', 'id'], name='application_player__7a54b4_idx'),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['c_years_of_experience', 'id'], name='application_c_years_1f93d4_idx'),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['c_last_name'], name='application_c_last__8c0d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='tennisplayer',
            index=models.Index(fields=['tp_last_name'], name='application_tp_last_30a41d_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['t_type', 'id'], name='application_t_type_0f40b6_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['t_name'], name='application_t_name_e5952c_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['tr_player', 'tr_tournament'], name='application_tr_play_091a97_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['tr_player'], name='application_tr_play_c4321d_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['tr_tournament'], name='application_tr_tour_1e2376_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['tr_registration_date'], name='application_tr_regi_f61a40_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['tr_last_year_performance'], name='application_tr_last_500f28_idx'),
        ),
    ]
